# Check for an interactive session
[ -z "$PS1" ] && return

# prompt
PS1='\[\e[32;1m\]>\[\e[35;1m\] \[\e[0m'

export GREP_COLOR="1;33"
export EDITOR="vim"

export TERM='xterm-256color'

# my binaries
PATH=${HOME}/.bin:${PATH}

# vi mode
set -o vi
